name: online_google_translator
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.0
  equatable: ^2.0.5
  http: ^1.2.1
  html: ^0.15.4
  http_parser: any
  image: any
  xml: ^6.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



